[env]
term = "xterm-256color"

[window.padding]
x = 5
y = 5

[font]
size = 5

[font.normal]
family = 'Fira Code Nerd Font'
style = 'semibold'

# Colors (Nordic)

[colors.primary]
#background = '#242933'
background = '#2E3440'
#foreground = '#BBBDAF'
foreground = '#FFFFFF'

[colors.normal]
#black = '#191C1D'
black = '#3b4252'
red = '#BD6062'
green = '#A3D6A9'
yellow = '#F0DFAF'
#blue = '#8FB4D8'
blue = '#81a1c1'
magenta = '#C7A9D9'
#cyan = '#B6D7A8'
cyan = '#88c0d0'
white = '#BDC5BD'

[colors.bright]
#black = '#727C7C'
black = '#4c566a'
red = '#D18FAF'
green = '#B7CEB0'
yellow = '#BCBCBC'
blue = '#E0CF9F'
magenta = '#C7A9D9'
cyan = '#BBDA97'
white = '#BDC5BD'

[colors.selection]
text = '#000000'
background = '#F0DFAF'
