require("plugged")
require("plugged.config.nord")
require("plugged.config.lualine")
require("plugged.config.bufferline")
require("plugged.config.gitsigns")
require("plugged.config.ibl")
require("plugged.config.telescope")
require("plugged.config.cmp")
require("plugged.config.luasnip")
require("plugged.config.treesitter")
require("plugged.config.autopairs")
require("plugged.config.lspconfig")

require("user.loadvim")
require("user.usercmd")
require("user.autocmd")
require("user.keybind")
