syntax on
let mapleader="\<space>"
colorscheme pablo

set clipboard^=unnamed,unnamedplus
set termguicolors encoding=UTF-8
set path+=**
set path-=**/node_modules/**
set timeoutlen=720
set mouse=a
set nocompatible
set updatetime=50
set autoread
set noswapfile nobackup
set undofile undodir=~/.vim/undo_dir
set hidden confirm showmode
set splitbelow splitright
set number relativenumber
set nowrap
set cursorline colorcolumn=80
set wildmenu
set fcs=eob:\ 
set hlsearch incsearch
set autoindent noexpandtab smartindent breakindent linebreak
set shiftwidth=2 tabstop=2 formatoptions=1 expandtab
set foldmethod=syntax
set viminfofile=$XDG_STATE_HOME/vim/viminfo

au CursorHold * checktime

" filetype config for unsupported files
au BufWinEnter *.txt set ft=help
au BufNewFile,BufRead *.edge set filetype=html
au BufNewFile,BufRead *.ino set filetype=cpp
au BufNewFile,BufRead *.html set filetype=htmldjango
au BufNewFile,BufRead *.md set textwidth=80

" indentation for slecific filetyles
au BufWinEnter *.templ setl shiftwidth=2 tabstop=2 noexpandtab
au BufWinEnter *.edge setl shiftwidth=2 tabstop=2 noexpandtab
au BufWinEnter *.html setl shiftwidth=2 tabstop=2 noexpandtab
au BufWinEnter *Makefile setl shiftwidth=2 tabstop=2 noexpandtab
au BufWinEnter *.go setl shiftwidth=4 tabstop=4
au BufWinEnter *.lua setl shiftwidth=3 tabstop=3 expandtab

" netrw custom layout
let g:netrw_liststyle=3
let g:netrw_list_hide=',\(^\|\s\s\)\zs\.\S\+'
let g:netrw_dirhistmax=0
command! MakeTags !ctags -R --exclude=.git --exclude=node_modules

" better <esc>
inoremap <c-l> <esc>
vnoremap <c-l> <esc>
snoremap <c-l> <esc>

" fix default vim behavior
nnoremap j gj
nnoremap k gk
nnoremap Y yg$
nnoremap J mzJ"z
nnoremap n nzzzv
nnoremap N Nzzzv

" buffer control and navigation
nnoremap <leader>q :q<cr>
nnoremap <leader>Q :qa!<cr>
nnoremap <c-s> :w!<cr>
inoremap <c-s> <esc>:w!<cr>
vnoremap <c-s> :w!<cr>
nnoremap <tab> :bn<cr>
nnoremap <s-tab> :bp<cr>
nnoremap <leader>bd :bdelete<cr>
nnoremap <leader>T :tabnew<cr>
nnoremap <leader><tab> :tabnext<cr>
nnoremap <leader><s-tab> :tabprevious<cr>

" window navigation and spliting
nnoremap <leader>i :vsplit<cr>
nnoremap <leader>s :split<cr>
nnoremap <leader>h <c-w>h
nnoremap <leader>j <c-w>j
nnoremap <leader>k <c-w>k
nnoremap <leader>l <c-w>l
nnoremap <leader>= <c-w>=

" file explorer (netrw)
nnoremap <leader>n :Ex<cr>
autocmd FileType netrw nnoremap <buffer> <leader>n <c-6>

" tag jumping keys
nnoremap <leader>0 '0zz
nnoremap <leader>1 '1zz
nnoremap <leader>2 '2zz
nnoremap <leader>3 '3zz
nnoremap <leader>4 '4zz
nnoremap <leader>5 '5zz
nnoremap <leader>6 '6zz
nnoremap <leader>7 '7zz
nnoremap <leader>8 '8zz
nnoremap <leader>9 '9zz
vnoremap <leader>0 '0zz
vnoremap <leader>1 '1zz
vnoremap <leader>2 '2zz
vnoremap <leader>3 '3zz
vnoremap <leader>4 '4zz
vnoremap <leader>5 '5zz
vnoremap <leader>6 '6zz
vnoremap <leader>7 '7zz
vnoremap <leader>8 '8zz
vnoremap <leader>9 '9zz

" change lines and indentation on the fly
nnoremap <leader><c-w> :setl wrap!<cr>
nnoremap <leader>: :set number! relativenumber!<cr>
nnoremap <leader>- :set colorcolumn=80<cr>
nnoremap <leader>+ :set colorcolumn=120<cr>
nnoremap <leader>II :set expandtab!<cr>
nnoremap <leader>I1 :set shiftwidth=2 tabstop=2<cr>
nnoremap <leader>I2 :set shiftwidth=4 tabstop=4<cr>
nnoremap <leader>I3 :set shiftwidth=8 tabstop=8<cr>

" editing helpers
nnoremap <leader>gg mzgg=G"z
inoremap <c-k> <cr><esc>O
nnoremap <f2> :%s/<c-r><c-w>//g<c-r><c-r><left><left><left>
nnoremap <leader>. A.<esc>
nnoremap <leader>, A,<esc>
nnoremap <leader>; A;<esc>
vnoremap J :m '>+1<cr>gv=gv
vnoremap K :m '<-2<cr>gv=gv
vnoremap <f2> :%s///<left><left>
nnoremap <leader><leader> @
xnoremap <leader>p "_dP

" developmet environment behavior
nnoremap <leader>t :term bash<cr>
nnoremap <c-p> :find ./**/*

if has("nvim")
  set laststatus=3  " use only one status bar for neovim
else
  set term=xterm-256color

  au BufWinEnter *.ino set ft=cpp

  " emulate autocomplete behavior
  inoremap / /<c-x><c-f><c-p>
  inoremap . .<c-n><c-p>
  inoremap ( (<c-n><c-p>
  inoremap [ [<c-n><c-p>
  inoremap { {<c-n><c-p>
  inoremap , ,<c-n><c-p>
  inoremap ) )<c-n><c-p>
  inoremap ] ]<c-n><c-p>
  inoremap } }<c-n><c-p>
endif

