function update_bashrc -d "Convert the fish/user/ files to a single ~/.bashrc file"
	set BASHPROMPT_FILE "$HOME/.config/fish/assets/prompt.bash"  #- Custom prompt to append to the final .bashrc file
	set GVARS_FILE "$HOME/.config/fish/user/gvariables.fish"     #- Global variables list file
	set ALIASRC_FILE "$HOME/.config/fish/user/aliasrc.fish"      #- File with the alias/abbr list written in a special syntax
	set BRC "$HOME/.bashrc"                                      #- I called this var that short to longer lines

	#- Displays an warnning message and then ask the user if it's ok to continue.
	printf "\n%s[WARNING]%s: This command will overwrite the %s~/.bashrc%s file!\n" \
		(set_color yellow) (set_color normal) (set_color -i cyan) (set_color normal)
	read -n1 -p 'printf "%s<read>%s Continue? %s[Y/n]%s " \\
	               (set_color black) (set_color normal) (set_color -i purple) (set_color normal)' answer
	echo

	string match -vr "$answer" '[Yy]' &>/dev/null &&
		return

	#- Generate a descritive message before parsing the Fish aliases & variables.
	echo "## AUTOGENERATED BASHRC CONFIG:" > "$BRC"
	echo "##  This ~/.bashrc file was automatically generated by a Fish (yeah the" >> "$BRC"
	echo "##  Fish shell) function, it has some of the same aliases and variables" >> "$BRC"
	echo "##  that this particular Fish config has!" >> "$BRC"
	echo "##" >> "$BRC"
	echo "##  More information at: http://github.com/kevinmarquesp" >> "$BRC"

	#- Actually parse the Fish config to Bash script, it's a little complicated, I know...
	sed 's/^#.*//;/^ *$/d;s/  */ /g;s/^set [^ ]* \([^ ]*\) /export \1=/' "$GVARS_FILE" >> "$BRC"                       #- Minify & parse the 'set -gx' syntax to 'export VARNAME='.
	awk '/\\\\$/ {printf("%s",substr($0,1,length($0)-1))} !/\\\\$/ {print}' "$ALIASRC_FILE" |                          #- Concatenate the lines ending with \ to the next one.
		sed 's/  */ /g;/^ *$/d;/#bign!/d;s/#binc: //g;/^#.*/d' |                                                       #- Include and exclude the commented Bash lines.
		sed 's/^if\(.*\)$/if\1; then/;s/end/fi/g;s/(\(.*\))/$(\1)/g;s/abbr/alias/;s/\(alias [^ =]*\) /\1=/' >> "$BRC"  #- Parse some of the Fish syntax to Bash.
	sed 's/^#.*//;/^ *$/d' "$BRCashprompt_file" >> "$BRC"                                                              #- Minify, just that...

	printf "%s[SUCCESS]%s: %s~/.bashrc%s file updated!\n\n" \
		(set_color green) (set_color normal) (set_color -i cyan) (set_color normal)
end
